type: google-cloud-function
version: 0.1.0
core: 0.2.x

description: "Provision Google Cloud Function"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    required: true
    default: func-${self.instanceId}
    displayName: Function name
    description: The Google Cloud Function name. Function names must be unique globally and match pattern projects/*/locations/*/functions/*
  description:
    type: string
    displayName: Function description
    description: A short, user-defined function description
  entryPoint:
    type: string
    displayName: Function entrypoint or handler
    description: The name of the function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified. For backward compatibility, if function with given name is not found, then the system will try to use function named "function". For Node.js this is name of a function exported by the module specified in source_location.
    example: helloworld
  timeout:
    type: string
    displayName: Execution timeout
    description: The Google Cloud Function execution timeout. Execution is considered failed and can be terminated if the function is not completed at the end of the timeout period. Defaults to 60 seconds. A duration in seconds with up to nine fractional digits, terminated by 's'.
    example: "3.5s"
  availableMemoryMb:
    type: number
    displayName: Available memory in MB
    description: The amount of memory in MB available for a function. Defaults to 256MB.
    example: 256
  labels:
    type: object
    displayName: Labels
    description: Labels associated with this Google Cloud Function. An object containing a list of key/value pairs.
    example: { "name": "wrench", "mass": "1.3kg", "count": "3" }
  sourceCodePath:
    type: string
    displayName: Path to source code
    example: ${self.path}/code
  sourceArchiveUrl:
    type: string
    displayName: Source code archive location
    description: The Google Cloud Storage URL, starting with gs://, pointing to the zip archive which contains the function.
  sourceRepository:
    type: object
    displayName: Source code repository location
    description: The source repository where a function is hosted. Of type '[sourceRepository](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#SourceRepository)'
    example: {"url": string, "deployedUrl": string}
  sourceUploadUrl:
    type: string
    displayName: Source code storage location
    description: The Google Cloud Storage signed URL used for source uploading, generated by [google.cloud.functions.v1.GenerateUploadUrl][].
  httpsTrigger:
    type: object
    displayName: Function https trigger
    description: An HTTPS endpoint type of source that can be triggered via URL. Of type '[HttpsTrigger](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#HttpsTrigger)'.
    example: {"url": string}
  eventTrigger:
    type: object
    displayName: Function event trigger
    description: A source that fires events in response to a condition in another service. Of type '[EventTrigger](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#EventTrigger)'.
    example: {"eventType": string, "resource": string, "service": string, "failurePolicy": {object(FailurePolicy)}}
  runtime:
    type: string
    default: nodejs6
    displayName: Runtime
    description: |
      Runtime for the function. If empty, defaults to nodejs6
      Possible values are java8, nodejs6, nodejs8, python2.7, python3.6 and dotnetcore1.0
  projectId:
    type: string
    required: true
    displayName: Project Id
    description: The Google Cloud Function project id
  locationId:
    type: string
    required: true
    displayName: Location Id
    description: The Google Cloud Function location id
    example: us-east1
  keyFilename:
    type: string
    required: true
    displayName: Credentials filename
    description: The Google Cloud Function credentials filename
    example: ~/.gcloud/keyfile.json
  env:
    type: object
    displayName: Environment variables
    description: Google Cloud function's environment configuration settings
  deploymentBucket:
    type: string
    displayName: Google Storage bucket name
    description: The name of the Google Storage bucket name where the function code is deployed

outputTypes:
  name:
    type: string
    description: The Google Cloud Function name. Function names must be unique globally and match pattern projects/*/locations/*/functions/*
  status:
    type: string
    description: The status of the Google Cloud function of type enum 'CloudFunctionStatus'.
  serviceAccountEmail:
    type: string
    description: The email of the Google Cloud Function's service account.
  updateTime:
    type: string
    description: The last updated timestamp of a Google Cloud Function in 'Timestamp' format. A timestamp in RFC3339 UTC "Zulu" format, accurate to nanoseconds, e.g. "2014-10-02T15:01:23.045123456Z".
  versionId:
    type: string
    description: The version identifier of the Google Cloud Function in 'int64' format. Each deployment attempt results in a new version of a function being created.
  entryPoint:
    type: string
    description: The name of the function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified. For backward compatibility, if function with given name is not found, then the system will try to use function named "function". For Node.js this is name of a function exported by the module specified in source_location.
  timeout:
    type: string
    description: The Google Cloud Function execution timeout. Execution is considered failed and can be terminated if the function is not completed at the end of the timeout period. Defaults to 60 seconds. A duration in seconds with up to nine fractional digits, terminated by 's'.
  availableMemoryMb:
    type: number
    description: The amount of memory in MB available for a function.
  runtime:
    type: string
    description: Runtime for the function.
  sourceArchiveFilename:
    type: string
    description: The filename of source code archive zip file.
  sourceArchiveUrl:
    type: string
    description: The Google Cloud Storage URL, starting with gs://, pointing to the zip archive which contains the function.
  httpsTrigger:
    type: object
    description: An HTTPS endpoint type of source that can be triggered via URL, of type 'HttpsTrigger'. The 'url' attribute is the deployed url for the function.
